# -*- coding: utf-8 -*-
"""3rdml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEX1Xao1VKfqdxEHjNOnJvW8R3LzXHfB
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile playtennis.csv
# Outlook,Temp,Humidity,Wind,Play
# Sunny,Hot,High,Weak,No
# Sunny,Hot,High,Strong,No
# Overcast,Hot,High,Weak,Yes
# Rain,Mild,High,Weak,Yes
# Rain,Cool,Normal,Weak,Yes
# Rain,Cool,Normal,Strong,No
# Overcast,Cool,Normal,Strong,Yes
# Sunny,Mild,High,Weak,No
# Sunny,Cool,Normal,Weak,Yes
# Rain,Mild,Normal,Weak,Yes

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

data = pd.read_csv("playtennis.csv")

le = LabelEncoder()

for col in data.columns:
    data[col] = le.fit_transform(data[col])

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

model = DecisionTreeClassifier(criterion="entropy")
model.fit(X, y)

sample = [[2,1,1,1]]

print("Prediction:", model.predict(sample))