# -*- coding: utf-8 -*-
"""4thml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiPtrgOti4Vu0XTwBzqrFlkObeC69gUk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ann.csv
# x1,x2,y
# 0,0,0
# 0,1,1
# 1,0,1
# 1,1,1

import pandas as pd
from sklearn.neural_network import MLPClassifier

data = pd.read_csv("ann.csv")

X = data[['x1','x2']]
y = data['y']

model = MLPClassifier(
    hidden_layer_sizes=(2,),
    max_iter=1000,
    random_state=1
)

model.fit(X, y)

print("Prediction:", model.predict([[1,0]]))


OUTPUT:
Prediction: [1]
