# -*- coding: utf-8 -*-
"""5thml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlgzeNIy4w6-bw-hb6w0w1uPcHGcQwww
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile knn.csv
# Age,Salary,Buy
# 22,20000,0
# 25,25000,0
# 47,50000,1
# 52,60000,1
# 46,52000,1
# 23,22000,0

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
data = pd.read_csv("knn.csv")

X = data[['Age','Salary']]
y = data['Buy']

model = KNeighborsClassifier(n_neighbors=3)

model.fit(X, y)

print("Prediction:", model.predict([[48,55000]]))

OUTPUT:
Prediction: [1]
